### ISSUE TITLE
Nations missing NF icons

### ISSUE THREAD

**Issue by Skodge** [maldun/autobahn#9] opened 2022-12-06 23:30 UTC
Hey, i ran KR alone and there were no missing icons.
After applying this mod i've found some countries missing NF icons:
Austrasia (AST): Victory of the new guard
![image](https://user-images.githubusercontent.com/99121181/206042933-32dfd794-527b-47ab-a01f-7a58c816fe86.png)
German east asia: (GEA): Valkiria thing
![image](https://user-images.githubusercontent.com/99121181/206043063-2912a47e-84cf-4c18-ab75-dc869d45a832.png)

I "fixed" it on my own machine by deleting the respected spritetypes (healthcare, new_guard) in "r56_goals" but i guess it affects something else.

Edit: Venezuela is missing like 3 icons, its a long way of sprites hunting.

**Comment by maldun** [comment] 2022-12-08 13:14
@Skodge Thanks for the report and providing me with a fix!
 
To my own shame this is one of the things which are left over from the early days of the mod where I didn't know what I am doing and just copied stuff from RT56.

The solution is fairly easy: Remove the said files and just put in the few GFX entries which actually matter. I also removed other stuff which should not necessary anymore.
This is fixed in 6316d3182b2aa98a0873fff3955d514def7b0ef9 and I will upload the new version as it should not mess with save games.

Thanks again!

**Comment by Skodge** [comment] 2022-12-08 13:40
@maldun I will test it this weekend, you removed all the spritetypes collectively? Or there are some left for other use?
First i thought by deleting these, i would mess something else like the focus tree you've built for centroamerica so i had to check the gfx bindings for each and every focus they had...

**Comment by maldun** [comment] 2022-12-08 18:14
@Skodge I don't mess with KR or KX focus trees, the only ones I added were the continuous ones, so this is rather simple for me to fix. I also don't remember that my mod had one for Centro America? If it differs it is definitely not by design.

**Comment by maldun** [comment] 2022-12-08 18:22
Ok I just checked, I indeed added Centro America, but this is an accident ... this should be removed as well.

**Comment by maldun** [comment] 2022-12-08 18:30
Ok this is fixed now in 245a67807b07697634e033791f7d1a24ee99cc66

I let the version for now as it is as there should be no conflicting images as all use KR assets anyway.

**Comment by Skodge** [comment] 2022-12-08 19:22
Looks like we hit 2 birds with 1 stone eh? I was about to ask if its possible to strip the additional features like centro america focus tree and run the mod as core rt56 mechanics added to KR.

**Comment by maldun** [comment] 2022-12-08 19:26
@Skodge Yeah it seems so, so thank you for that! 

However, the Focus tree is there because of Naval tech. The solution will be a short patch script which just adds the latest KR tree on each update. So there should be no future conflicts whatsoever.

**Comment by maldun** [comment] 2022-12-08 23:01
Ok after I checked if the tech is still there I found that the new KR version does not uses any cv_naval_bombers anymore. So the file can be removed for good and no additional change has to be made.

This patch will come with the next release. Since it will likely destroy saves I will leave it be for now.

**Closed** 2022-12-09 01:40 UTC
