### ISSUE TITLE
Unknown crash occuring

### ISSUE THREAD

**Issue by banburak11** [maldun/autobahn#16] opened 2023-01-22 16:24 UTC
Crash occurs spontaneously around 10-20 days into this gameplay
[POL_1939_08_20_12.zip](https://github.com/maldun/autobahn/files/10474902/POL_1939_08_20_12.zip)
Crash report
[hoi4_20230122_170859.zip](https://github.com/maldun/autobahn/files/10474903/hoi4_20230122_170859.zip)
I dont really have any idea how to diagnose this

**Comment by maldun** [comment] 2023-01-23 18:49
Hi! Thx for the report.

The mod is indeed outdated as KX was updated recently. (Fixed in 3e3f3d94c80c80febb67af3dcfe0e8f5b5fae49e )

Nevertheless, this does not save your save file, as the crash is rather weird: When Siam takes the capital of Burma the crash happens ... and this is not resolved by the update. You can however save the game when you just switch to Siam and annex Burma (They would have lost anyway in a few weeks ...)

It can be KX or it could be caused by the outdated scripts, I can' t pin-point the issue exactly, but I hope this resolves it. Update is up btw. I let the issue open for now, if something happens again please let me know.

Have fun!

**Comment by banburak11** [comment] 2023-01-24 08:50
Thank You :) 
That's the diagnose I needed, I was supposing that some of the wars going on is the reason.
While there were ~15 of them going on I had no idea where is the problem. 
Thanks again for fast update. 
Cheers

**Closed** 2023-02-23 23:46 UTC
