### ISSUE TITLE
game crashes when hovering over shock troop doctrine

### ISSUE THREAD

**Issue by Sexyknight** [maldun/autobahn#31] opened 2023-10-17 08:47 UTC
game crashes when hovering over certain shock troop doctrine icons

**Comment by po8crg** [comment] 2023-10-21 01:39
Yeah, I see this too.

**Comment by po8crg** [comment] 2023-10-21 02:05
I've tried to pin this one down a bit, but I don't really understand the graphics part of modding.

Anyway, it seems to crash when opening the special forces doctrine screen after a few seconds of having it open, so you can hover over a few doctrines, but then you get a CTD.

**Comment by maldun** [comment] 2023-10-26 17:17
Is this still relevant? I could not reproduce the issue and on the Steam Workshop page someone already confirmed it was solved with the latest KR patch.

**Comment by po8crg** [comment] 2023-10-26 22:29
I force updated everything and that fixed it.

**Comment by Sexyknight** [comment] 2023-10-27 03:15
just tested it, seems to be fixed now. thank you!

**Comment by maldun** [comment] 2023-10-31 22:49
Perfect I will close the issue now with this

**Closed by maldun** 2023-10-31 22:49 UTC
